// <auto-generated />
using System;
using ESDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESDB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210923054702_initEsdbTables")]
    partial class initEsdbTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ESDB.Models.config_data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<bool>("disabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("msCreatorId");

                    b.Property<int>("msLastUpdatorId");

                    b.Property<int>("order");

                    b.Property<int>("quantity");

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.ToTable("config_data");
                });

            modelBuilder.Entity("ESDB.Models.config_module", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<bool>("disabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("iconPath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<string>("moduleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("msCreatorId");

                    b.Property<int>("msLastUpdatorId");

                    b.Property<int>("order");

                    b.HasKey("id");

                    b.ToTable("config_module");
                });

            modelBuilder.Entity("ESDB.Models.sys_dictionary", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<string>("key")
                        .HasMaxLength(50);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("order");

                    b.Property<string>("parentKey")
                        .HasMaxLength(50);

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<byte>("type");

                    b.Property<string>("value")
                        .HasMaxLength(300);

                    b.HasKey("id");

                    b.ToTable("sys_dictionary");
                });

            modelBuilder.Entity("ESDB.Models.sys_log", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("logParams")
                        .HasMaxLength(4000);

                    b.Property<DateTime>("logTime");

                    b.Property<int>("logType");

                    b.Property<string>("logUrl")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("requestIp")
                        .HasMaxLength(30);

                    b.Property<int>("userId");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("sys_log");
                });

            modelBuilder.Entity("ESDB.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("avatar")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("birthday");

                    b.Property<DateTime>("createTime");

                    b.Property<bool>("disabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("email")
                        .HasMaxLength(50);

                    b.Property<byte?>("gender");

                    b.Property<string>("idNo")
                        .HasMaxLength(30);

                    b.Property<int?>("idType");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<string>("mobile")
                        .HasMaxLength(30);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("realname")
                        .HasMaxLength(30);

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("types")
                        .HasMaxLength(20);

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ESDB.Models.user_expert", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<bool>("govReview");

                    b.Property<string>("govReviewName")
                        .HasMaxLength(500);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("researchResult")
                        .HasMaxLength(2000);

                    b.Property<bool>("transferResult");

                    b.Property<string>("types")
                        .HasMaxLength(10);

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("user_expert");
                });

            modelBuilder.Entity("ESDB.Models.user_files", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("type");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("user_files");
                });

            modelBuilder.Entity("ESDB.Models.user_info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("degree");

                    b.Property<int>("eduLevel");

                    b.Property<string>("graduatedSchool")
                        .HasMaxLength(50);

                    b.Property<string>("industries")
                        .HasMaxLength(50);

                    b.Property<string>("job")
                        .HasMaxLength(50);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("nativePlace")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("researchArea")
                        .HasMaxLength(50);

                    b.Property<string>("titles")
                        .HasMaxLength(50);

                    b.Property<string>("unitAddress")
                        .HasMaxLength(100);

                    b.Property<string>("unitAddressCode")
                        .HasMaxLength(30);

                    b.Property<string>("unitName")
                        .HasMaxLength(50);

                    b.Property<string>("unitType")
                        .HasMaxLength(20);

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("user_info");
                });
#pragma warning restore 612, 618
        }
    }
}
