spring:
  datasource:
    ms:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.11:3306/msdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: YCCloud_@0769
    rs:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.11:3306/rsdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: YCCloud_@0769
  redis:
    database: 0
    host: 192.168.125.11
    port: 6379
   # password: 123456

dingDingConfig:
  #dingoaippdherp6i9tuynn
  agentId: 302821533
  appKey: dingxrsmrn4ae1cecwgk
  appSecret: dnKvwmzm0nJ36yFbC58FK0K8ymf01Rocu2gL-S5tl552eij4eRv72msnag-2ZQgp

commonConfig:
  picUrl: http://project.gdyskc.com:9000/img/logo.af1ca756.png
  projectProgressUrl: http://project.gdyskc.com:9000/customer/ProjectProgress
wx:
  appid: wx8b70a679db801527
  secret: ce3307523ea8484d67ece8b37db424f9
  msgTemplateId: ZHHVbNwOpy2gYBWRG5FYRb5IgqQIyGXS99WoIWTUIaQ
kafka:
  bootstrapServers: 192.168.0.99:9092
  producer:
    #  clientId: 0
    acks: 1
    retries: 5
    batchSize: 16384
    lingerMs: 5

