// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSDB;

namespace RSDB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190906014909_d_design_deptId")]
    partial class d_design_deptId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RSDB.Models.accountTitle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("accountName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("accoutType");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("parentId");

                    b.HasKey("id");

                    b.ToTable("accountTitle");
                });

            modelBuilder.Entity("RSDB.Models.app_menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fullPath")
                        .HasMaxLength(300);

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<byte>("level");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("parentId");

                    b.Property<string>("perms");

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<byte>("seq");

                    b.Property<byte>("status");

                    b.Property<byte>("type");

                    b.Property<string>("url")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.ToTable("app_menu");
                });

            modelBuilder.Entity("RSDB.Models.app_role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("remark")
                        .HasMaxLength(100);

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("app_role");
                });

            modelBuilder.Entity("RSDB.Models.app_role_menu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("menuId");

                    b.Property<int>("roleId");

                    b.HasKey("id");

                    b.ToTable("app_role_menu");
                });

            modelBuilder.Entity("RSDB.Models.app_user_role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("roleId");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("app_user_role");
                });

            modelBuilder.Entity("RSDB.Models.company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("accountSystem")
                        .HasMaxLength(20);

                    b.Property<string>("addressCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("businessLicense")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("capital")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("companyAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("creditCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("depts");

                    b.Property<string>("domain")
                        .HasMaxLength(100);

                    b.Property<string>("email")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("firstDevFee");

                    b.Property<byte>("from");

                    b.Property<bool>("hasDevAccount");

                    b.Property<bool>("highTec");

                    b.Property<string>("highTecIndustry")
                        .HasMaxLength(20);

                    b.Property<string>("industryCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("invoiceTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("linkMan")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("linkTel")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("mainIndustry")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("members");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("realTaxAuthorities")
                        .HasMaxLength(30);

                    b.Property<DateTime>("registerTime");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<byte>("status");

                    b.Property<string>("taxAuthorities")
                        .HasMaxLength(30);

                    b.Property<string>("taxpayerId")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("RSDB.Models.d_attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("attData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("month");

                    b.Property<string>("remainAttData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasDefaultValue("0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.ToTable("d_attendance");
                });

            modelBuilder.Entity("RSDB.Models.d_bonus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("beginDay");

                    b.Property<decimal>("bonus")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("endDay");

                    b.Property<DateTime>("endTime");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("isUsed");

                    b.Property<DateTime>("month");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<DateTime>("startTime");

                    b.Property<decimal>("totalBonus")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.HasIndex("companyId", "enumber", "month")
                        .IsUnique();

                    b.ToTable("d_bonus");
                });

            modelBuilder.Entity("RSDB.Models.d_design", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("dFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("deptId");

                    b.Property<DateTime>("designDate");

                    b.Property<string>("dname")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("rdDeptId");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.ToTable("d_design");
                });

            modelBuilder.Entity("RSDB.Models.d_energy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("deptId");

                    b.Property<string>("ename");

                    b.Property<DateTime>("occDate");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("rdDeptId");

                    b.Property<decimal>("remainRatio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<int>("type");

                    b.Property<string>("unit")
                        .HasMaxLength(10);

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.ToTable("d_energy");
                });

            modelBuilder.Entity("RSDB.Models.d_equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("depreciation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ecode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("equData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<DateTime>("month");

                    b.Property<string>("remainEquData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasDefaultValue("0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<int>("workHours");

                    b.HasKey("id");

                    b.HasIndex("ecode", "month", "companyId")
                        .IsUnique();

                    b.ToTable("d_equipment");
                });

            modelBuilder.Entity("RSDB.Models.d_inspection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("accDate");

                    b.Property<string>("accNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("deptId");

                    b.Property<decimal>("expense")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("rdDeptId");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.ToTable("d_inspection");
                });

            modelBuilder.Entity("RSDB.Models.d_material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("accNumber")
                        .HasMaxLength(20);

                    b.Property<DateTime>("acqDate");

                    b.Property<string>("auditor")
                        .HasMaxLength(30);

                    b.Property<string>("billNo")
                        .HasMaxLength(30);

                    b.Property<string>("biller")
                        .HasMaxLength(30);

                    b.Property<string>("booker")
                        .HasMaxLength(30);

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("deptId");

                    b.Property<string>("mcode")
                        .HasMaxLength(50);

                    b.Property<string>("mname")
                        .HasMaxLength(200);

                    b.Property<string>("picker")
                        .HasMaxLength(30);

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("rdDeptId");

                    b.Property<decimal>("remainQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("specification")
                        .HasMaxLength(200);

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("type");

                    b.Property<string>("unit")
                        .HasMaxLength(10);

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("warehouse")
                        .HasMaxLength(30);

                    b.HasKey("id");

                    b.ToTable("d_material");
                });

            modelBuilder.Entity("RSDB.Models.d_salary", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("dayHours");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal>("endowment")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("endowmentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("house")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("houseOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("injury")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("injuryOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("insuranceFund")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("maternity")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("maternityOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("medical")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("medicalOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("month");

                    b.Property<decimal>("pay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<decimal>("unemployment")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("unemploymentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("workDays")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("id");

                    b.ToTable("d_salary");
                });

            modelBuilder.Entity("RSDB.Models.dept", b =>
                {
                    b.Property<short>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("deptName");

                    b.Property<string>("fullPath")
                        .HasMaxLength(300);

                    b.Property<string>("identity")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<int>("level");

                    b.Property<short>("parentId");

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.HasKey("id");

                    b.ToTable("dept");
                });

            modelBuilder.Entity("RSDB.Models.docProcess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<int>("lastMsUpdatorId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("msCreatorId");

                    b.Property<string>("processName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("remark")
                        .HasMaxLength(100);

                    b.Property<int>("type");

                    b.HasKey("id");

                    b.ToTable("docProcess");
                });

            modelBuilder.Entity("RSDB.Models.docProcessTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("enabled");

                    b.Property<bool>("optional");

                    b.Property<int>("processId");

                    b.Property<int>("seq");

                    b.Property<int>("templateId");

                    b.HasKey("id");

                    b.ToTable("docProcessTemplate");
                });

            modelBuilder.Entity("RSDB.Models.docTemplate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createTime");

                    b.Property<string>("docName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("lastMsUpdatorId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("msCreatorId");

                    b.Property<string>("templatePath")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("version")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("id");

                    b.ToTable("docTemplate");
                });

            modelBuilder.Entity("RSDB.Models.employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("deptId");

                    b.Property<DateTime>("edate");

                    b.Property<int>("eduLevel");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("etype");

                    b.Property<string>("idNumber")
                        .HasMaxLength(20);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("rdDeptId");

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<string>("title")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("RSDB.Models.equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("depreciation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("depreciationDate");

                    b.Property<decimal>("depreciationRate")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("deptId");

                    b.Property<string>("ecode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("emodal")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("etype");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<DateTime>("purchaseDate");

                    b.Property<int>("quantity");

                    b.Property<int>("rdDeptId");

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("usagePower");

                    b.Property<int>("usefullife");

                    b.HasKey("id");

                    b.HasIndex("companyId", "ecode")
                        .IsUnique();

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("RSDB.Models.i_equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<int>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("ecode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("projectId");

                    b.HasKey("id");

                    b.ToTable("i_equipment");
                });

            modelBuilder.Entity("RSDB.Models.i_member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("projectId");

                    b.HasKey("id");

                    b.ToTable("i_member");
                });

            modelBuilder.Entity("RSDB.Models.insuranceConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("endowment")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("endowmentOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("house")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("houseOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("injury")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("injuryOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<decimal>("maternity")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("maternityOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("medical")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("medicalOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("unemployment")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("unemploymentOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<int>("updatorId");

                    b.HasKey("id");

                    b.HasIndex("companyId")
                        .IsUnique();

                    b.ToTable("insuranceConfig");
                });

            modelBuilder.Entity("RSDB.Models.p_attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("attData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("attendanceDataId");

                    b.Property<decimal>("bonus")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("dayHours");

                    b.Property<decimal>("endowmentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("hasModify");

                    b.Property<decimal>("houseOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("injuryOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("insuranceFund")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<decimal>("maternityOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("medicalOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("month");

                    b.Property<decimal>("pay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("projectId");

                    b.Property<decimal>("rdBonus")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdDays")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("rdEndowmentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdHouseOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdInjuryOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdInsuranceFund")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("rdMaternityOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdMedicalOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("rdPay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("rdUnemploymentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("unemploymentOfCom")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.ToTable("p_attendance");
                });

            modelBuilder.Entity("RSDB.Models.p_attendance_month", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("hoursAttData")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<DateTime>("month");

                    b.Property<string>("personAttData")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("projectId");

                    b.HasKey("id");

                    b.HasIndex("companyId", "projectId", "month")
                        .IsUnique();

                    b.ToTable("p_attendance_month");
                });

            modelBuilder.Entity("RSDB.Models.p_attendance_used", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("month");

                    b.Property<int>("remainHours");

                    b.Property<string>("usedAttData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("workHours");

                    b.HasKey("id");

                    b.HasIndex("companyId", "enumber", "month")
                        .IsUnique();

                    b.ToTable("p_attendance_used");
                });

            modelBuilder.Entity("RSDB.Models.p_design", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("designDataId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("projectId");

                    b.HasKey("id");

                    b.ToTable("p_design");
                });

            modelBuilder.Entity("RSDB.Models.p_document", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("docName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("docNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("processId");

                    b.Property<int>("projectId");

                    b.Property<int>("stageId");

                    b.Property<int>("templateId");

                    b.HasKey("id");

                    b.ToTable("p_document");
                });

            modelBuilder.Entity("RSDB.Models.p_energy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("energyDataId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("projectId");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("rdAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("used")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("usedRatio")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.ToTable("p_energy");
                });

            modelBuilder.Entity("RSDB.Models.p_equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("depreciation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ecode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("equData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("equipmentDataId");

                    b.Property<bool>("hasModify");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<DateTime>("month");

                    b.Property<int>("projectId");

                    b.Property<decimal>("rdDepreciation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("rdHour");

                    b.HasKey("id");

                    b.ToTable("p_equipment");
                });

            modelBuilder.Entity("RSDB.Models.p_equipment_used", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<string>("ecode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("month");

                    b.Property<int>("remainHours");

                    b.Property<string>("usedEquData")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int>("workHours");

                    b.HasKey("id");

                    b.HasIndex("companyId", "ecode", "month")
                        .IsUnique();

                    b.ToTable("p_equipment_used");
                });

            modelBuilder.Entity("RSDB.Models.p_inspection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("inspectionDataId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("projectId");

                    b.HasKey("id");

                    b.ToTable("p_inspection");
                });

            modelBuilder.Entity("RSDB.Models.p_material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("materialDataId");

                    b.Property<int>("projectId");

                    b.Property<int>("rdType");

                    b.Property<decimal>("used")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("id");

                    b.ToTable("p_material");
                });

            modelBuilder.Entity("RSDB.Models.p_project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("beginDate");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<int>("deptId");

                    b.Property<string>("deptIds")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("endDate");

                    b.Property<int>("estimateExpense");

                    b.Property<string>("masterENumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("pname");

                    b.Property<int>("rdDeptId");

                    b.Property<int>("rdIndex");

                    b.Property<int>("reportId");

                    b.Property<string>("tecIndustry")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("p_project");
                });

            modelBuilder.Entity("RSDB.Models.p_report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("rname")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ryear");

                    b.HasKey("id");

                    b.ToTable("p_report");
                });

            modelBuilder.Entity("RSDB.Models.p_stage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("beginDate");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<DateTime>("endDate");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("projectId");

                    b.Property<string>("remark")
                        .HasMaxLength(200);

                    b.Property<string>("stageName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("p_stage");
                });

            modelBuilder.Entity("RSDB.Models.p_summary", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<DateTime>("month");

                    b.Property<int>("projectId");

                    b.Property<decimal>("rdFunds")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("rdType");

                    b.Property<int>("updatorId");

                    b.HasKey("id");

                    b.HasIndex("projectId", "month", "rdType")
                        .IsUnique();

                    b.ToTable("p_summary");
                });

            modelBuilder.Entity("RSDB.Models.p_worktimeRatio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("auxiliary")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<decimal>("laboratory")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<DateTime>("month");

                    b.Property<decimal>("production")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("projectId");

                    b.Property<decimal>("research")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("technical")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("id");

                    b.ToTable("p_worktimeRatio");
                });

            modelBuilder.Entity("RSDB.Models.rdDept", b =>
                {
                    b.Property<short>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("deptName");

                    b.Property<string>("identity")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<int>("level");

                    b.Property<short>("parentId");

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.HasKey("id");

                    b.ToTable("rdDept");
                });

            modelBuilder.Entity("RSDB.Models.sys_dictionary", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("key")
                        .HasMaxLength(50);

                    b.Property<int>("order");

                    b.Property<string>("parentKey")
                        .HasMaxLength(50);

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<byte>("type");

                    b.Property<string>("value")
                        .HasMaxLength(300);

                    b.HasKey("id");

                    b.ToTable("sys_dictionary");
                });

            modelBuilder.Entity("RSDB.Models.sys_insuranceConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<int>("deptId");

                    b.Property<DateTime?>("endMonth");

                    b.Property<decimal>("endowment")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("endowmentOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("enumber")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("house")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("houseOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("injury")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("injuryOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("maternity")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("maternityOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("medical")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("medicalOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.Property<DateTime>("startMonth");

                    b.Property<decimal>("unemployment")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("unemploymentOfCom")
                        .HasColumnType("decimal(6,4)");

                    b.HasKey("id");

                    b.ToTable("sys_insuranceConfig");
                });

            modelBuilder.Entity("RSDB.Models.sys_session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createTime");

                    b.Property<DateTime>("expireTime");

                    b.Property<string>("token")
                        .HasMaxLength(50);

                    b.Property<DateTime>("updateTime");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("sys_session");
                });

            modelBuilder.Entity("RSDB.Models.sys_tableField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("fieldTitle")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("tableId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("id");

                    b.ToTable("sys_tableField");
                });

            modelBuilder.Entity("RSDB.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("avatar")
                        .HasMaxLength(20);

                    b.Property<int>("companyId");

                    b.Property<DateTime>("createTime");

                    b.Property<int>("creatorId");

                    b.Property<string>("email")
                        .HasMaxLength(100);

                    b.Property<byte>("gender");

                    b.Property<DateTime>("lastUpdateTime");

                    b.Property<int>("lastUpdatorId");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("realName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("remark")
                        .HasMaxLength(300);

                    b.Property<byte>("status");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<byte>("type");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
